### ISSUE TITLE
Comments inside a text block

### ISSUE THREAD

**Issue by RazrFalcon** [crdoconnor/strictyaml#101]
```yaml
# comment
text: | # comment
  # not a comment
```

Maybe "comments" inside a text block should be forbidden to remove ambiguity?

**Comment by crdoconnor** [comment]
Yep, I that sounds like a good idea.

**Comment by crdoconnor** [comment]
Not sure if it should be forbidden or should parse as text though.

**Comment by RazrFalcon** [comment]
yaml parses it as text, which is unexpected.

**Comment by crdoconnor** [comment]
Actually I'm starting to think it should be expected for the 3rd comment to be parsed as text (definitely not the 1st, not sure what to do about the 2nd).

I also can't see how you'd include a block of text that includes lines which begin with # otherwise. I use strictyaml for python code snippets a lot so this scenario isn't unusual at all for me.

**Comment by RazrFalcon** [comment]
This is just a suggestion. I don't mind having comments inside a text block. 

Feel free to close it.

**Comment by crdoconnor** [comment]
There are certain issues like this where the principle of least surprise
might be violated for which I'd prefer to go to the wider community for
confirmation but I think I might bundle it into that and close this issue.
