### ISSUE TITLE
Basic documentation for validators

### ISSUE THREAD

**Issue by AlexandreDecan** [crdoconnor/strictyaml#2]
Could you please provide, eg. in the *README*, some examples showing how to use the different validators provided by your library? 

For instance, I see in the code there is an ``Optional`` validator, a support for disjunctive validators, etc. but this is not mentioned in the "documentation" nor in some examples. 

I assume those are pretty intuitive to use (ie. ``Optional(Str())``, or ``Str() | Int()``). Am I right?

**Comment by crdoconnor** [comment]
Yep, exactly right. Those should have been in there. I've just added them now.

**Comment by AlexandreDecan** [comment]
You should also mention that "OR" is satisfied from "left to right", meaning that if you have a field that contains ``42``, then a validator ``Str() | Int()`` will map the value to a string, and a validator ``Int() | Str()`` will map the value to an integer.

**Comment by andres-fr** [comment]
Hi, sorry for reopening. I'm new to `strictyaml`, it was an eye-opener to me for some daunting issues with regular YAML. Thanks!

I just wanted to point out that it is taking me a while to figure out how to validate `YAML` objects when they are already in-memory, without going through the process of re-loading them.

As far as I can tell, the documentation shows validation only in the context of `load(data, schema)`. After searching through the code, I found the `YAML.revalidate` method, which seems to fit the bill:

https://github.com/crdoconnor/strictyaml/blob/a4844dec6d52f62c2b97363d9de97fa09c9a69ce/strictyaml/representation.py#L55

Is this correct? If not, what would be the best way to subject an existing (potentially mutable) YAML object to a specific validation schema?

Cheers and thanks again for the amazing SW!
aferro

**Comment by andres-fr** [comment]
After trying things out a little more it seems now to me that `.revalidate` does not fit the bill.

One important feature of `strictyaml` is that contents are loaded as strings unless specified otherwise via a schema. This must happen upon `load` in the lifecycle, and not after.

For this reason, if a `YAML` object has been loaded as a string, calling `revalidate` with a specific schema will trigger an error containing something like the following:

```
my_yaml.revalidate(my_schema)
*** strictyaml.exceptions.YAMLValidationError: when expecting an integer
  in "<unicode string>", line 205, column 1:
      x: '123'
    ^ (line: 205)
found arbitrary text
```

The give away is the **found arbitrary text** error.

So I guess the only meaningful solution is indeed to **convert to string via `as_yaml` and then parse again with the specific schema**, as follows:

```
validated_yaml = strictyaml.load(initial_yaml.as_yaml(), schema=MY_SCHEMA)
```

Did I get it right this time?
